spring.application.name=BikeRideProject
server.port=8081
spring.data.mongodb.uri=mongodb+srv://ride:ride@cluster1.b6f0i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
spring.data.mongodb.database=BikeRide
spring.data.mongodb.auto-index-creation=true
aws.access.key.id=AKIASIVGK3F3CT7L4XXZ
aws.secret.access.key=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
aws.s3.region=eu-north-1
aws.s3.bucket=zyromile
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#mongodb+srv://test:<db_password>@ride.ptyeo.mongodb.net/?retryWrites=true&w=majority&appName=Ride

#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BikeRide;encrypt=false
#spring.datasource.username=sa
#spring.datasource.password=hrhk@5050
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


#username=ride and password=ride   